<?php

declare(strict_types=1);

namespace DoctrineMigrations;

// phpcs:disable Generic.Files.LineLength.TooLong

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\AbstractMigration;

final class Version20260828210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store StackHal blog articles and SEO content in the database';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS blog_articles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(160) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, category VARCHAR(80) NOT NULL, read_time_minutes SMALLINT NOT NULL, published_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, content_html TEXT NOT NULL, cta_label VARCHAR(160) NOT NULL, cta_path VARCHAR(160) NOT NULL, visual_class VARCHAR(80) NOT NULL, visual_lines JSON NOT NULL, how_to_steps JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_blog_articles_slug ON blog_articles (slug)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_blog_articles_published_at ON blog_articles (published_at)');

        $publishedAt = new \DateTimeImmutable('2026-08-28 00:00:00+00:00');
        $articles = [
            ['bimi-not-working', 'BIMI Not Working? A Practical Guide to DMARC, SVG Tiny PS, DNS Records, and VMC', 'Diagnose DMARC enforcement, SVG Tiny PS, DNS records, HTTPS hosting, and VMC or CMC certificate requirements.', 'Email authentication', 8, 'bimi', ['v=BIMI1', 'p=reject', 'SVG Tiny PS'], 'Open BIMI Studio', '/bimi-studio', '<p>BIMI is a DNS-published signal that lets participating mailbox providers consider showing your brand logo next to authenticated email. It is not a replacement for SPF, DKIM, or DMARC.</p><div class="article-callout article-callout-accent"><strong>The useful mental model</strong><span>DMARC proves the sender is allowed to use the domain. BIMI tells a mailbox where the brand mark lives. The mailbox provider still decides whether to display it.</span></div><h2>Check DMARC before touching the logo</h2><p>For BIMI eligibility, use <code>p=quarantine</code> or <code>p=reject</code> with <code>pct=100</code>. A monitoring-only <code>p=none</code> policy is not enough for providers that require enforcement.</p><h2>Publish the exact BIMI record</h2><pre class="article-code"><code>default._bimi.example.com. IN TXT "v=BIMI1; l=https://example.com/logo-bimi.svg;"</code></pre><p>Check the exact DNS name, HTTPS logo URL, MIME type, and cached answers. BIMI uses the stricter SVG Tiny PS profile, and some providers require VMC or CMC certificates.</p><h2>Troubleshooting checklist</h2><ol class="article-checklist"><li>Confirm the visible From domain.</li><li>Verify DMARC enforcement and alignment.</li><li>Query <code>default._bimi.domain</code>.</li><li>Check SVG retrieval and profile constraints.</li><li>Check provider-specific certificate requirements.</li></ol>', [['Enforce DMARC', 'Use quarantine or reject with pct=100.'], ['Prepare the logo', 'Create a square SVG Tiny PS logo.'], ['Publish the record', 'Publish a TXT record at default._bimi.yourdomain.'], ['Inspect the result', 'Check DNS, SVG reachability, MIME type, and provider requirements.']]],
            ['nginx-to-caddy', 'Nginx to Caddy Migration: Common Rewrite Rules and Hidden Traps', 'A practical migration guide with real equivalents for locations, proxy_pass, redirects, headers, and path prefixes.', 'Reverse proxies', 9, 'caddy', ['location /api/', 'reverse_proxy', 'header_up Host'], 'Open Caddyfile Transpiler', '/caddy-transpiler', '<p>Caddy is not a line-for-line Nginx replacement. Identify the matcher, handler, and response behavior in each Nginx block, then express those things in Caddy directive order.</p><div class="article-callout article-callout-accent"><strong>The useful mental model</strong><span>Nginx chooses a location and runs directives inside it. Caddy builds a handler chain from matchers and directives, so ordering and path semantics deserve a review.</span></div><h2>Translate location blocks</h2><pre class="article-code"><code># Nginx
location /api/ { proxy_pass http://backend:8080/; }

# Caddy
handle /api/* {
  uri strip_prefix /api
  reverse_proxy backend:8080
}</code></pre><p>A prefix location becomes a path matcher. A broad <code>location /</code> is usually a fallback handler. Keep narrow routes explicit.</p><h2>proxy_pass and path prefixes</h2><p>In Nginx, the trailing slash controls whether the matched location prefix is replaced. Caddy forwards the request path by default, so use <code>uri strip_prefix</code> when the upstream expects a different path.</p><h2>Redirects and headers</h2><pre class="article-code"><code># Nginx
return 301 https://$host$request_uri;
proxy_set_header Host $host;
add_header Cache-Control "public, max-age=3600";

# Caddy
redir https://{host}{uri} permanent
reverse_proxy app:3000 {
  header_up Host {host}
}

// phpcs:enable Generic.Files.LineLength.TooLong
header Cache-Control "public, max-age=3600"</code></pre><p><code>header_up</code> changes what the application receives; <code>header</code> changes what the browser receives. Check both with a real request.</p><h2>Migration checklist</h2><ol class="article-checklist"><li>Run <code>caddy validate --config Caddyfile</code>.</li><li>Test prefixed routes and upstream URIs.</li><li>Compare redirects and query strings.</li><li>Inspect response and upstream request headers.</li><li>Test missing files, slash variants, OPTIONS, and 404s.</li></ol>', [['Map the site address', 'Convert server_name and listen into a site address.'], ['Translate matchers', 'Map location blocks to path or named matchers.'], ['Translate proxy behavior', 'Use reverse_proxy and header_up for upstream routing.'], ['Validate and reload', 'Validate, compare behavior, and keep rollback ready.']]],
            ['dns-delegation-explained', 'DNS Delegation Explained: From Root to Authoritative Nameserver', 'Follow a DNS lookup across recursive resolution, delegation, glue, authoritative data, and DNSSEC.', 'DNS', 8, 'dns', ['root → .com', 'NS → auth', 'DNSSEC ✓'], 'Open DNS DAG Tracer', '/dns-dag-tracer', '<p>When a recursive resolver looks up <code>www.example.com</code>, it follows referrals down a hierarchy until an authoritative nameserver can answer for the zone that contains the name.</p><figure class="article-visual dns-chain"><div class="dns-node"><b>ROOT</b><span>.</span><small>refers to .com</small></div><i>↓</i><div class="dns-node"><b>TLD</b><span>.com</span><small>refers to example.com</small></div><i>↓</i><div class="dns-node dns-node-result"><b>AUTHORITATIVE</b><span>203.0.113.42</span><small>final answer</small></div><figcaption>A delegation is a referral from a parent zone to a child zone.</figcaption></figure><h2>Root, TLD, and delegation</h2><p>The root zone knows which nameservers serve each TLD. The TLD returns the delegation for <code>example.com</code>: NS names and sometimes glue. The child zone begins at that delegation cut.</p><pre class="article-code"><code>example.com. 172800 IN NS ns1.dns-host.example
www.example.com. 300 IN A 203.0.113.42</code></pre><h2>NS records and glue</h2><p>An NS record names a server. Glue is an address supplied by the parent when the nameserver hostname lives inside the child zone, preventing a circular dependency.</p><h2>Recursive resolvers and DNSSEC</h2><p>A recursive resolver performs the root-to-authority walk, caches answers according to TTL, and returns the result to the client. DNSSEC adds signatures: a validating resolver follows DS, DNSKEY, and RRSIG records back to a trusted root. It authenticates DNS data but does not encrypt traffic. A broken chain can produce <code>SERVFAIL</code>, unlike <code>NXDOMAIN</code>.</p><h2>Trace checklist</h2><ol class="article-checklist"><li>Ask the root for the TLD referral.</li><li>Ask the TLD for the child NS set and glue.</li><li>Query the exact record at the authoritative server.</li><li>Separate cached answers from authoritative answers.</li><li>Check TTLs and validate DS, DNSKEY, and RRSIG.</li></ol>', [['Start at the root', 'Ask a root server for the requested TLD.'], ['Follow the TLD delegation', 'Ask the TLD for the domain delegation and NS records.'], ['Resolve the nameserver address', 'Use glue for an in-bailiwick nameserver hostname.'], ['Query the authority', 'Ask the authoritative server for the final record and validate DNSSEC.']]],
            ['pkpass-signature-errors', 'PKPass Signature Errors: What to Check Before Rebuilding the Bundle', 'Diagnose PKPass signatures by checking ZIP structure, manifest SHA-1 hashes, detached PKCS#7, and certificates.', 'Apple Wallet', 7, 'pkpass', ['manifest.json', 'SHA-1 ✓', 'signature PKCS#7'], 'Open PKPass Inspector', '/apple-pkpass-inspector', '<p>A <code>.pkpass</code> is a ZIP archive with a strict top-level layout. A signature failure is often caused by one changed byte, one nested directory, or one file missing from the manifest.</p><figure class="article-visual pkpass-structure"><div class="package-folder"><b>event.pkpass</b><code>pass.json</code><code>manifest.json</code><code>signature</code><code>icon.png</code></div><div class="package-flow"><span>files</span><b>SHA-1</b><span>manifest.json</span><b>PKCS#7</b><span>signature</span></div><figcaption>The manifest describes bytes; the detached signature protects the manifest.</figcaption></figure><h2>Start with manifest.json and SHA-1</h2><p>The manifest maps each pass file to its SHA-1 digest. Hash the exact bytes stored in the archive. One changed newline, recompressed image, or case change produces a different digest.</p><pre class="article-code"><code>{
  "pass.json": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b",
  "icon.png": "2bb80d537b1da3e38bd30361aa855686bde0ba9a"
}</code></pre><h2>The detached PKCS#7 signature</h2><p>The <code>signature</code> file signs the exact bytes of <code>manifest.json</code>. Signing a different serialization will fail verification.</p><h2>Certificate chain and packaging</h2><p>The signing certificate must be valid for pass signing and chained to the Apple WWDR intermediate and a trusted root. Check the team identifier, private-key pairing, top-level ZIP layout, MIME type, and delivered bytes.</p><h2>Pre-rebuild checklist</h2><ol class="article-checklist"><li>Confirm the archive root layout.</li><li>Recalculate every manifest SHA-1 from archive bytes.</li><li>Verify the signature against the exact manifest.</li><li>Inspect the full certificate chain and team identifier.</li><li>Download the delivered file and compare its hash.</li></ol>', [['Inspect the bundle', 'Confirm required files are at the top level.'], ['Recalculate hashes', 'Compare SHA-1 values byte-for-byte with manifest.json.'], ['Verify the signature', 'Check that PKCS#7 signs the exact manifest bytes.'], ['Check certificates and packaging', 'Validate the WWDR chain and ZIP layout.']]],
        ];

        foreach ($articles as $article) {
            $this->addSql(
                'INSERT INTO blog_articles (slug, title, description, category, read_time_minutes, published_at, updated_at, content_html, cta_label, cta_path, visual_class, visual_lines, how_to_steps) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                [$article[0], $article[1], $article[2], $article[3], $article[4], $publishedAt, $publishedAt, $article[9], $article[7], $article[8], $article[5], $article[6], $article[10]],
                [Types::STRING, Types::STRING, Types::TEXT, Types::STRING, Types::SMALLINT, Types::DATETIMETZ_IMMUTABLE, Types::DATETIMETZ_IMMUTABLE, Types::TEXT, Types::STRING, Types::STRING, Types::STRING, Types::JSON, Types::JSON]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS blog_articles');
    }
}
