<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823012000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial PostgreSQL persistence schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE IF NOT EXISTS leads ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'email VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, message TEXT NOT NULL, '
            . 'ip_hash VARCHAR(64) NOT NULL, source VARCHAR(50) NOT NULL, '
            . 'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at)');

        $this->addSql(
            'CREATE TABLE IF NOT EXISTS page_views ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, visitor_hash VARCHAR(64) NOT NULL, '
            . 'path VARCHAR(255) NOT NULL, source VARCHAR(50) NOT NULL, '
            . 'referrer_host VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_page_views_occurred_at ON page_views (occurred_at)');

        $this->addSql(
            'CREATE TABLE IF NOT EXISTS price_observations ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_slug VARCHAR(100) NOT NULL, '
            . 'observed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, median_grosz INT NOT NULL, '
            . 'low_grosz INT NOT NULL, high_grosz INT NOT NULL, sample_size INT NOT NULL, '
            . 'confidence VARCHAR(20) NOT NULL, summary TEXT DEFAULT NULL, '
            . 'methodology TEXT NOT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_product_observed_at ON price_observations (product_slug, observed_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_observations_product_slug ON price_observations (product_slug)');

        $this->addSql(
            'CREATE TABLE IF NOT EXISTS price_tips ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_slug VARCHAR(100) NOT NULL, '
            . 'listing_url VARCHAR(2048) NOT NULL, email VARCHAR(255) NOT NULL, '
            . 'ip_hash VARCHAR(64) NOT NULL, submitted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            . 'expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_tips_expires_at ON price_tips (expires_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_tips_submitted_at ON price_tips (submitted_at)');

        $this->addSql(
            'CREATE TABLE IF NOT EXISTS product_requests ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, '
            . 'email VARCHAR(255) NOT NULL, ip_hash VARCHAR(64) NOT NULL, '
            . 'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_requests_created_at ON product_requests (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS page_views');
        $this->addSql('DROP TABLE IF EXISTS price_tips');
        $this->addSql('DROP TABLE IF EXISTS price_observations');
        $this->addSql('DROP TABLE IF EXISTS product_requests');
        $this->addSql('DROP TABLE IF EXISTS leads');
    }
}
