<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823012000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial PostgreSQL persistence schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE IF NOT EXISTS leads ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'email VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, message TEXT NOT NULL, '
            . 'ip_hash VARCHAR(64) NOT NULL, source VARCHAR(50) NOT NULL, '
            . 'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at)');

        $this->addSql(
            'CREATE TABLE IF NOT EXISTS page_views ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, visitor_hash VARCHAR(64) NOT NULL, '
            . 'path VARCHAR(255) NOT NULL, source VARCHAR(50) NOT NULL, '
            . 'referrer_host VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_page_views_occurred_at ON page_views (occurred_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS page_views');
        $this->addSql('DROP TABLE IF EXISTS leads');
    }
}
