<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap · Bahdan Hal</title>
        <style>
          :root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
          * { box-sizing: border-box; }
          body { margin: 0; color: #e7eef8; background: radial-gradient(circle at 12% 0%, #23466f 0, transparent 34rem), linear-gradient(145deg, #12233a, #0d1828 55%, #101d31); min-height: 100vh; }
          main { width: min(1120px, calc(100% - 32px)); margin: 0 auto; padding: 64px 0 80px; }
          .eyebrow { color: #73b7ff; font-size: 12px; font-weight: 900; letter-spacing: .14em; }
          h1 { margin: 14px 0 10px; font: 700 clamp(38px, 6vw, 68px)/1 Georgia, serif; letter-spacing: -.04em; }
          p { color: #aab9cd; line-height: 1.6; }
          .summary { margin-bottom: 34px; }
          .count { color: #fff; font-weight: 800; }
          .table { overflow-x: auto; border: 1px solid #314762; border-radius: 14px; background: rgba(14, 27, 45, .9); }
          table { width: 100%; border-collapse: collapse; }
          th, td { padding: 15px 18px; text-align: left; border-bottom: 1px solid #293b55; }
          th { color: #8eadd1; background: #162a43; font-size: 11px; letter-spacing: .08em; text-transform: uppercase; }
          tr:last-child td { border-bottom: 0; }
          a { color: #83c2ff; text-decoration: none; overflow-wrap: anywhere; }
          a:hover { text-decoration: underline; }
          .date { color: #9aaac0; white-space: nowrap; }
          .language { display: inline-block; margin-right: 7px; padding: 4px 7px; border: 1px solid #3d5c80; border-radius: 99px; color: #b8d9ff; font-size: 10px; font-weight: 800; text-transform: uppercase; }
          footer { margin-top: 22px; color: #8294aa; font-size: 12px; }
          @media (max-width: 650px) { main { padding-top: 38px; } th, td { padding: 12px; } .alternates { display: none; } }
        </style>
      </head>
      <body>
        <main>
          <div class="eyebrow">SEARCH ENGINE DISCOVERY</div>
          <h1>XML Sitemap</h1>
          <p class="summary">This standards-compliant sitemap contains <span class="count"><xsl:value-of select="count(sm:urlset/sm:url)"/></span> canonical, indexable URLs. The readable view is supplied by XSL; search engines receive the underlying XML.</p>
          <div class="table">
            <table>
              <thead><tr><th>URL</th><th>Last updated</th><th class="alternates">Languages</th></tr></thead>
              <tbody>
                <xsl:for-each select="sm:urlset/sm:url">
                  <tr>
                    <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                    <td class="date"><xsl:choose><xsl:when test="sm:lastmod"><xsl:value-of select="sm:lastmod"/></xsl:when><xsl:otherwise>—</xsl:otherwise></xsl:choose></td>
                    <td class="alternates">
                      <xsl:for-each select="xhtml:link[@hreflang != 'x-default']"><a class="language" href="{@href}"><xsl:value-of select="@hreflang"/></a></xsl:for-each>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>
          <footer>Generated by Bahdan’s Toolbox · <a href="https://bahdanhal.pl/">bahdanhal.pl</a></footer>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
